(() => {
  const { createClient } = window.supabase;
  const client = createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
  const app = document.querySelector('#app');
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const errorText = error => error?.message || 'Die Anfrage konnte nicht verarbeitet werden.';
  const layout = content => `<div class="shell"><aside class="sidebar"><div class="brand"><span class="cross"></span><span>DEUTSCHES ROTES KREUZ<small>Sanitätslager</small></span></div><nav class="nav"><button data-view="dashboard">Übersicht</button><button data-view="backpacks">Sanitätsrucksäcke</button><button data-view="reports">Verbrauchsmeldungen</button><button data-view="items">Artikel & Bestand</button><button data-view="users" data-admin-only>Benutzerverwaltung</button></nav><button id="logout" class="button secondary side-bottom">Abmelden</button></aside><main class="main"><header class="topbar"><div><small>SANITÄTSLAGER</small><h1 id="title">Übersicht</h1></div><button class="button primary" data-new-item>+ Artikel</button></header><section id="view" class="content">${content}</section></main></div>`;
  const status = value => `<span class="badge ${value === 'gebucht' ? 'success' : value === 'offen' ? 'warning' : 'danger-badge'}">${esc(value)}</span>`;
  let state = { profile: null, items: [], backpacks: [], reports: [], users: [] };
  async function load() { const [items, backpacks, reports, users] = await Promise.all([client.from('items').select('*').eq('active', true).order('name'), client.from('backpacks').select('*, backpack_items(*)').order('id'), client.from('reports').select('*').order('created_at', { ascending: false }), state.profile.role === 'admin' ? client.from('profiles').select('*').order('name') : Promise.resolve({ data: [] })]); const result = [items, backpacks, reports, users].find(row => row.error); if (result) throw result.error; state.items = items.data || []; state.backpacks = backpacks.data || []; state.reports = reports.data || []; state.users = users.data || []; }
  function dashboard() { const open = state.reports.filter(item => item.status === 'offen'); return `<div class="intro"><p class="eyebrow">LAGERSTATUS</p><h2>Alles Wichtige auf einen Blick.</h2><p class="muted">Verbrauch prüfen und Rucksäcke wieder einsatzbereit machen.</p></div><div class="metrics"><div class="metric"><strong>${state.items.length}</strong><span>Artikel</span></div><div class="metric"><strong>${state.backpacks.length}</strong><span>Rucksäcke</span></div><div class="metric"><strong>${state.items.filter(item => item.stock <= item.minimum).length}</strong><span>Bestandswarnungen</span></div><div class="metric"><strong>${open.length}</strong><span>Offene Meldungen</span></div></div><div class="grid"><section class="panel"><h3>Sanitätsrucksäcke</h3><div class="list">${state.backpacks.map(pack => `<div class="list-row"><strong>${esc(pack.name)}</strong><small>${esc(pack.identifier)}</small></div>`).join('')}</div></section><section class="panel"><h3>Offene Meldungen</h3><div class="list">${open.map(report => `<div class="list-row"><strong>Rucksack ${report.backpack_id}</strong><small>${esc(report.reporter_name)}</small></div>`).join('') || '<p class="empty">Keine offenen Meldungen.</p>'}</div></section></div>`; }
  function backpacks() { return `<div class="intro"><p class="eyebrow">BESTAND</p><h2>Sanitätsrucksäcke</h2></div><div class="backpacks">${state.backpacks.map(pack => `<article class="panel"><p class="eyebrow">${esc(pack.identifier)}</p><h3>${esc(pack.name)}</h3><p class="muted">${pack.backpack_items.length} Packlistenpositionen</p><button class="button primary" data-refill="${pack.id}">Auffüllen</button></article>`).join('')}</div>`; }
  function reports() { return `<div class="intro"><p class="eyebrow">EINGEGANGEN</p><h2>Verbrauchsmeldungen</h2></div><section class="panel table-wrap"><table class="table"><thead><tr><th>Rucksack</th><th>Helfer</th><th>Verbrauch</th><th>Status</th><th></th></tr></thead><tbody>${state.reports.map(report => `<tr><td>${report.backpack_id}</td><td>${esc(report.reporter_name)}</td><td>${(report.entries || []).map(entry => `${entry.amount}x ${esc(entry.name)}`).join('<br>')}</td><td>${status(report.status)}</td><td>${report.status === 'offen' ? `<button class="button primary" data-book="${report.id}">Buchen</button>` : ''}</td></tr>`).join('') || '<tr><td colspan="5" class="empty">Noch keine Meldungen.</td></tr>'}</tbody></table></section>`; }
  function items() { return `<div class="intro"><p class="eyebrow">LAGERBESTAND</p><h2>Artikel & Bestand</h2></div><section class="panel table-wrap"><table class="table"><thead><tr><th>Artikel</th><th>Bestand</th><th>Warnschwelle</th><th>Einheit</th></tr></thead><tbody>${state.items.map(item => `<tr><td>${esc(item.name)}</td><td>${item.stock}</td><td>${item.minimum}</td><td>${esc(item.unit)}</td></tr>`).join('') || '<tr><td colspan="4" class="empty">Noch keine Artikel.</td></tr>'}</tbody></table></section>`; }
  function users() { return `<div class="intro"><p class="eyebrow">ZUGÄNGE</p><h2>Benutzerverwaltung</h2><p class="muted">Benutzer werden in Supabase Auth angelegt. Hier verwaltest du Rolle und Aktivstatus.</p></div><section class="panel table-wrap"><table class="table"><thead><tr><th>Name</th><th>E-Mail</th><th>Rolle</th><th>Status</th><th></th></tr></thead><tbody>${state.users.map(user => `<tr><td>${esc(user.name)}</td><td>${esc(user.id)}</td><td><select data-role="${user.id}"><option value="admin" ${user.role === 'admin' ? 'selected' : ''}>Administrator</option><option value="lager" ${user.role === 'lager' ? 'selected' : ''}>Lagerteam</option></select></td><td><input type="checkbox" data-active="${user.id}" ${user.active ? 'checked' : ''}></td><td><button class="button secondary" data-save-user="${user.id}">Speichern</button></td></tr>`).join('')}</tbody></table></section>`; }
  const screens = { dashboard, backpacks, reports, items, users };
  async function render(view = 'dashboard') { try { await load(); app.innerHTML = layout(screens[view]()); document.querySelectorAll('[data-view]').forEach(button => { button.classList.toggle('active', button.dataset.view === view); button.onclick = () => render(button.dataset.view); }); document.querySelector('[data-admin-only]').classList.toggle('hidden', state.profile.role !== 'admin'); document.querySelector('#logout').onclick = async () => { await client.auth.signOut(); renderLogin(); }; document.querySelectorAll('[data-book]').forEach(button => button.onclick = () => book(button.dataset.book)); document.querySelectorAll('[data-refill]').forEach(button => button.onclick = () => refill(button.dataset.refill)); document.querySelectorAll('[data-save-user]').forEach(button => button.onclick = () => saveUser(button.dataset.saveUser)); document.querySelector('[data-new-item]').onclick = addItem; } catch (error) { app.innerHTML = `<main class="login"><p class="error">${esc(errorText(error))}</p></main>`; } }
  async function book(id) { const report = state.reports.find(item => item.id === id); if (!report) return; for (const entry of report.entries || []) { const current = await client.from('backpack_items').select('stock').eq('backpack_id', report.backpack_id).eq('item_id', entry.item_id).single(); if (current.error) return alert(errorText(current.error)); const nextStock = Math.max(0, current.data.stock - Number(entry.amount)); const changed = await client.from('backpack_items').update({ stock: nextStock }).match({ backpack_id: report.backpack_id, item_id: entry.item_id }); if (changed.error) return alert(errorText(changed.error)); } const { error } = await client.from('reports').update({ status: 'gebucht', resolved_at: new Date().toISOString() }).eq('id', id); if (error) return alert(errorText(error)); render('reports'); }
  async function refill(id) { const { data, error } = await client.from('backpack_items').select('item_id,target_quantity,stock').eq('backpack_id', id); if (error) return alert(errorText(error)); for (const row of data) { const amount = Math.max(0, row.target_quantity - row.stock); if (amount) { await client.from('backpack_items').update({ stock: row.stock + amount }).match({ backpack_id: id, item_id: row.item_id }); const item = state.items.find(candidate => candidate.id === row.item_id); if (item) await client.from('items').update({ stock: Math.max(0, item.stock - amount) }).eq('id', item.id); } } render('backpacks'); }
  function addItem() { const name = prompt('Artikelname'); if (!name) return; client.from('items').insert({ name, unit: 'Stück' }).then(({ error }) => error ? alert(errorText(error)) : render('items')); }
  async function saveUser(id) { const role = document.querySelector(`[data-role="${id}"]`).value; const active = document.querySelector(`[data-active="${id}"]`).checked; const { error } = await client.from('profiles').update({ role, active }).eq('id', id); if (error) alert(errorText(error)); else render('users'); }
  function renderLogin() { app.innerHTML = `<main class="login"><section class="login-form"><div class="brand"><span class="cross"></span><span>DEUTSCHES ROTES KREUZ<small>Sanitätslager</small></span></div><h1>Anmelden</h1><form id="login" class="form"><label>E-Mail<input name="email" type="email" required></label><label>Passwort<input name="password" type="password" required></label><button class="button primary">Anmelden</button><p id="error" class="error"></p></form></section><aside class="login-side"><h2>Alles im Blick. Schnell wieder aufgefüllt.</h2></aside></main>`; document.querySelector('#login').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.target); const { error } = await client.auth.signInWithPassword({ email: form.get('email'), password: form.get('password') }); if (error) document.querySelector('#error').textContent = errorText(error); else start(); }; }
  async function start() { const { data } = await client.auth.getSession(); if (!data.session) return renderLogin(); const profile = await client.from('profiles').select('*').eq('id', data.session.user.id).single(); if (profile.error) return renderLogin(); state.profile = profile.data; render(); }
  start();
})();
