(() => {
  const { createClient } = window.supabase;
  const client = createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
  const app = document.querySelector('#helper-app');
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  async function start() {
    const [backpacks, items] = await Promise.all([client.from('backpacks').select('id,name,identifier,backpack_items(item_id,target_quantity)').order('id'), client.from('items').select('id,name,unit').eq('active', true).order('name')]);
    if (backpacks.error || items.error) { app.innerHTML = '<p class="error">Die Materialliste konnte nicht geladen werden.</p>'; return; }
    app.innerHTML = `<main class="helper"><div class="brand"><span class="cross"></span><span>DEUTSCHES ROTES KREUZ<small>Sanitätsdienst</small></span></div><p class="eyebrow">MOBILE VERBRAUCHSLISTE</p><h1>Materialverbrauch melden</h1><p class="muted">Wähle den Rucksack und trage ein, was verbraucht wurde.</p><form id="report" class="panel form"><label>Rucksack<select name="backpack" required><option value="">Bitte auswählen</option>${backpacks.data.map(pack => `<option value="${pack.id}">${esc(pack.name)} · ${esc(pack.identifier)}</option>`).join('')}</select></label><label>Dein Name<input name="name" required></label><label>Bemerkung<textarea name="note" rows="3"></textarea></label><div id="rows"></div><button type="button" class="button secondary" id="add">+ Material hinzufügen</button><p id="error" class="error"></p><button class="button primary">Verbrauch melden</button></form></main>`;
    const rows = document.querySelector('#rows'); const packSelect = document.querySelector('[name=backpack]');
    const addRow = () => { const pack = backpacks.data.find(item => item.id === Number(packSelect.value)); const row = document.createElement('div'); row.className = 'helper-entry'; row.innerHTML = `<label>Artikel<select name="item" required>${(pack?.backpack_items || []).map(entry => { const item = items.data.find(candidate => candidate.id === entry.item_id); return item ? `<option value="${item.id}">${esc(item.name)} (${esc(item.unit)})</option>` : ''; }).join('')}</select></label><label>Menge<input name="amount" type="number" min="1" value="1" required></label>`; rows.append(row); };
    addRow(); const refreshRows = () => { const pack = backpacks.data.find(item => item.id === Number(packSelect.value)); rows.querySelectorAll('[name=item]').forEach(select => { select.innerHTML = (pack?.backpack_items || []).map(entry => { const item = items.data.find(candidate => candidate.id === entry.item_id); return item ? `<option value="${item.id}">${esc(item.name)} (${esc(item.unit)})</option>` : ''; }).join(''); }); }; packSelect.onchange = refreshRows; document.querySelector('#add').onclick = addRow;
    document.querySelector('#report').onsubmit = async event => { event.preventDefault(); const form = event.target; const entries = [...rows.querySelectorAll('.helper-entry')].map(row => { const item = items.data.find(candidate => candidate.id === row.querySelector('[name=item]').value); return { item_id: item.id, name: item.name, amount: Number(row.querySelector('[name=amount]').value) }; }); const { error } = await client.from('reports').insert({ backpack_id: Number(form.backpack.value), reporter_name: form.name.value, note: form.note.value, entries }); if (error) document.querySelector('#error').textContent = error.message; else form.innerHTML = '<h2>Danke!</h2><p class="muted">Die Verbrauchsmeldung wurde an das Lager gesendet.</p>'; };
  }
  start();
})();
